name: 🐛 Reportar bug
description: Use para reportar erros, falhas ou comportamentos inesperados.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        **Preencha TODOS os campos** abaixo para acelerar a investigação.
  - type: input
    id: description
    attributes:
      label: Descrição do problema
      placeholder: "Ex: Ao clicar em 'Salvar', recebo erro 500 no console."
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      placeholder: |
        1. Logar no sistema  
        2. Navegar até /cadastro  
        3. Preencher nome e clicar em salvar
      required: true
  - type: input
    id: expected
    attributes:
      label: Comportamento esperado
      required: true
  - type: input
    id: actual
    attributes:
      label: Comportamento atual
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      options:
        - Blocker
        - Critical
        - Major
        - Minor
        - Trivial
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Ambiente (SO, browser, versão)
  - type: textarea
    id: attachments
    attributes:
      label: Anexos (screenshots, logs)
